// <auto-generated />
namespace DataPhotography.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Exercise6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exercise6));
        
        string IMigrationMetadata.Id
        {
            get { return "201703111003331_Exercise6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
